"""empty message

Revision ID: 872ec51a7298
Revises: 6c836dd17a81
Create Date: 2020-03-17 11:47:39.806507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '872ec51a7298'
down_revision = '6c836dd17a81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('bio', sa.String(length=75), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'bio')
    # ### end Alembic commands ###
